///
/// @Generated by Mockolo
///



import BigInt
import CryptoSwift
import Foundation


public class JSONRPCProviderProtocolMock: JSONRPCProviderProtocol {
    public init() { }


    public private(set) var sendCallCount = 0
    public var sendHandler: ((Any) async throws -> (Any))?
    public func send<R: JSONRPCRequest>(_ request: R) async throws -> R.Response {
        sendCallCount += 1
        if let sendHandler = sendHandler {
            return try await sendHandler(request) as! R.Response
        }
        fatalError("sendHandler returns can't have a default value thus its handler must be set")
    }
}

